In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
havaDurumu = pd.read_csv("2018-2021.csv")

havaDurumu

In [3]:
havaDurumu.head()

STATION_NAME        DATE      TIME  PM10  SO2   NO2   O3   CO  AQI_INDEX  \
0       Maslak  02.01.2018  16:00:00  37.7  0.0  29.6  1.8  0.0         14   
1       Maslak  02.01.2018  17:00:00  25.0  0.0  30.0  1.8  0.0         15   
2       Maslak  02.01.2018  18:00:00  30.0  0.0  30.3  1.3  0.0         15   
3       Maslak  02.01.2018  19:00:00  43.2  0.0  29.8  1.9  0.0         15   
4       Maslak  02.01.2018  20:00:00  28.9  0.0  29.5  1.8  0.0         14   

   STATE  
0      1  
1      1  
2      1  
3      1  
4      1

## sbn.pairplot(havaDurumu)

In [4]:
 from sklearn.model_selection import train_test_split

In [5]:
y = havaDurumu["AQI_INDEX"].values
x = havaDurumu[["PM10","SO2","NO2"]].values
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3,random_state=20)

In [6]:
x_train.shape

(515169, 3)

In [7]:
x_test.shape

(343447, 3)

In [8]:
y_train.shape

(515169,)

In [9]:
y_test.shape

(343447,)

In [10]:
x_train

array([[ 15.7,   0. ,  75.2],
       [ 26.9,   0. ,  20.4],
       [ 70.6,   6.4, 277.1],
       ...,
       [ 36.8,   1.6,  29.7],
       [ 64.1,   3.1,  90.9],
       [ 14.2,   2.5,   0. ]])

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler = MinMaxScaler()

In [13]:
scaler.fit(x_train)

MinMaxScaler()

In [1]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

NameError: name 'scaler' is not defined

In [15]:
x_train

array([[0.00615559, 0.03570114, 0.13137174],
       [0.00880724, 0.03570114, 0.07459594],
       [0.01915337, 0.04747884, 0.34055118],
       ...,
       [0.0111511 , 0.03864556, 0.08423125],
       [0.01761447, 0.04140596, 0.1476378 ],
       [0.00580046, 0.0403018 , 0.05346042]])

In [16]:
import tensorflow as tf

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
model = Sequential()
model.add(Dense(4,activation="relu"))
model.add(Dense(4,activation="relu"))
model.add(Dense(4,activation="relu"))
# 4 verilen nöran sayısı 3 gizli katmanlı 4 nöron
model.add(Dense(1))
model.compile(optimizer = "rmsprop", loss = "mse")
# kullanılan optimizasyo algoritmaları için compile içine yazılırr. Compile birleştirir kodu hazır hale getirir.
# rmsprop, en çok kullanılan adam.
# mse regression hata mesajı eksileri artılara çevirmek için MSE regression yaz bak.

In [19]:
model.fit(x_train,y_train,epochs=250)

Epoch 1/250
16100/16100 [==============================] - 14s 852us/step - loss: 388.4487
Epoch 2/250
16100/16100 [==============================] - 15s 914us/step - loss: 229.0910
Epoch 3/250
16100/16100 [==============================] - 13s 813us/step - loss: 215.9061
Epoch 4/250
16100/16100 [==============================] - 12s 753us/step - loss: 214.5904
Epoch 5/250
16100/16100 [==============================] - 13s 832us/step - loss: 214.0075
Epoch 6/250
16100/16100 [==============================] - 11s 669us/step - loss: 208.7103
Epoch 7/250
16100/16100 [==============================] - 11s 710us/step - loss: 202.8502
Epoch 8/250
16100/16100 [==============================] - 12s 763us/step - loss: 200.4392
Epoch 9/250
16100/16100 [==============================] - 12s 721us/step - loss: 199.3801
Epoch 10/250
16100/16100 [==============================] - 11s 679us/step - loss: 198.7790
Epoch 11/250
16100/16100 [==============================] - 12s 715us/step - loss: 198.49

16100/16100 [==============================] - 11s 664us/step - loss: 196.0541
Epoch 179/250
16100/16100 [==============================] - 11s 673us/step - loss: 196.5311
Epoch 180/250
16100/16100 [==============================] - 11s 674us/step - loss: 196.2756
Epoch 181/250
16100/16100 [==============================] - 11s 658us/step - loss: 195.7838
Epoch 182/250
16100/16100 [==============================] - 11s 671us/step - loss: 196.8644
Epoch 183/250
16100/16100 [==============================] - 11s 672us/step - loss: 196.5451
Epoch 184/250
16100/16100 [==============================] - 11s 676us/step - loss: 196.2120
Epoch 185/250
16100/16100 [==============================] - 11s 677us/step - loss: 196.3779
Epoch 186/250
16100/16100 [==============================] - 11s 674us/step - loss: 196.1633
Epoch 187/250
16100/16100 [==============================] - 11s 656us/step - loss: 196.1543
Epoch 188/250
16100/16100 [==============================] - 11s 672us/step - loss: 

In [20]:

havaDurumu

STATION_NAME        DATE      TIME  PM10   SO2   NO2   O3   CO  \
0            Maslak  02.01.2018  16:00:00  37.7   0.0  29.6  1.8  0.0   
1            Maslak  02.01.2018  17:00:00  25.0   0.0  30.0  1.8  0.0   
2            Maslak  02.01.2018  18:00:00  30.0   0.0  30.3  1.3  0.0   
3            Maslak  02.01.2018  19:00:00  43.2   0.0  29.8  1.9  0.0   
4            Maslak  02.01.2018  20:00:00  28.9   0.0  29.5  1.8  0.0   
...             ...         ...       ...   ...   ...   ...  ...  ...   
858611        Tuzla  13.12.2021  20:00:00  25.0   8.9  55.9  1.9  0.0   
858612        Tuzla  13.12.2021  21:00:00  11.0   8.8  59.4  2.5  0.0   
858613        Tuzla  13.12.2021  22:00:00   9.0   9.5  50.9  2.8  0.0   
858614        Tuzla  13.12.2021  23:00:00  15.0   9.0  51.4  3.6  0.0   
858615        Tuzla  14.12.2021  00:00:00  10.0  10.0  39.7  4.9  0.0   

        AQI_INDEX  STATE  
0              14      1  
1              15      1  
2              15      1  
3              15      1  
4              14      1  
...           ...    ...  
858611         27      1  
858612         29      1  
858613         25      1  
858614         25      1  
858615         20      1  

[858616 rows x 10 columns]

In [22]:
havaDurumu.isnull().sum()

STATION_NAME    0
DATE            0
TIME            0
PM10            0
SO2             0
NO2             0
O3              0
CO              0
AQI_INDEX       0
STATE           0
dtype: int64

In [26]:
havaDurumu = havaDurumu.drop(columns=["STATION_NAME"])

In [28]:
havaDurumu.head()

DATE      TIME  PM10  SO2   NO2   O3   CO  AQI_INDEX  STATE
0  02.01.2018  16:00:00  37.7  0.0  29.6  1.8  0.0         14      1
1  02.01.2018  17:00:00  25.0  0.0  30.0  1.8  0.0         15      1
2  02.01.2018  18:00:00  30.0  0.0  30.3  1.3  0.0         15      1
3  02.01.2018  19:00:00  43.2  0.0  29.8  1.9  0.0         15      1
4  02.01.2018  20:00:00  28.9  0.0  29.5  1.8  0.0         14      1

In [29]:
y = havaDurumu["AQI_INDEX"].values
x = havaDurumu.drop(["AQI_INDEX"],axis=1).values

In [30]:
x

array([['02.01.2018', '16:00:00', 37.7, ..., 1.8, 0.0, 1],
       ['02.01.2018', '17:00:00', 25.0, ..., 1.8, 0.0, 1],
       ['02.01.2018', '18:00:00', 30.0, ..., 1.3, 0.0, 1],
       ...,
       ['13.12.2021', '22:00:00', 9.0, ..., 2.8, 0.0, 1],
       ['13.12.2021', '23:00:00', 15.0, ..., 3.6, 0.0, 1],
       ['14.12.2021', '00:00:00', 10.0, ..., 4.9, 0.0, 1]], dtype=object)

In [31]:
y

array([14, 15, 15, ..., 25, 25, 20], dtype=int64)

In [34]:
from sklearn.preprocessing import MinMaxScaler()

In [36]:
scaler = MinMaxScaler()

In [37]:
x_train = scaler.fit_transform(x_train)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [38]:
x_train.shape

(515169, 3)