In [1]:
import numpy as np

In [2]:
ilkListe = [10,20,30]

## array

In [9]:
ilkArray = np.array(ilkListe)

In [10]:
ilkArray

array([10, 20, 30])

In [11]:
type(ilkArray)

numpy.ndarray

In [12]:
matrixListesi = [10,20,30],[40,50,60,],[60,70,80]

In [14]:
matrixListesi[0][1]

20

In [15]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [60, 70, 80]])

## arange = python range aynı mantık sıralı liste

In [16]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros = 0 olan listeler

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## ones = bir olan listeler

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace = belirtilen sayı kadar sayıyı eşit uzaklıkta göster

In [34]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

## eye = matrix oluşturur 

In [35]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [44]:
np.random.randn(4,4)

array([[ 0.45021063, -0.6964405 , -0.28976718, -1.7578772 ],
       [ 0.69452723,  0.88066554,  0.37753852, -1.01018849],
       [ 0.37311973, -0.91161684, -0.70138232,  0.73802584],
       [ 0.49576086,  0.38333302, -1.19623108,  0.904397  ]])

In [53]:
np.random.randint(1,10,100)

array([5, 4, 7, 4, 6, 1, 2, 4, 3, 4, 6, 7, 4, 3, 6, 5, 5, 1, 2, 6, 8, 1,
       9, 7, 1, 2, 2, 1, 4, 8, 5, 9, 7, 5, 1, 5, 2, 6, 2, 9, 8, 8, 2, 7,
       6, 8, 7, 8, 6, 2, 8, 1, 9, 8, 9, 7, 5, 5, 6, 4, 1, 4, 9, 3, 1, 9,
       2, 5, 4, 1, 8, 2, 1, 8, 6, 4, 4, 3, 3, 2, 6, 2, 7, 6, 4, 1, 9, 2,
       8, 1, 4, 1, 3, 2, 4, 6, 9, 6, 7, 2])

In [60]:
randomDizi = np.random.randint(2,500,8)

In [61]:
randomDizi

array([169,  70, 199, 142, 435, 323, 340,  20])

## numpy dizi methodları

In [59]:
randomDizi.reshape(1)

ValueError: cannot reshape array of size 2 into shape (1,)

In [62]:
iNumpyArray = np.arange(30)

In [63]:
iNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
iNumpyArray.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
randomDizi.max()

435

In [67]:
randomDizi.argmax()

4

In [68]:
randomDizi.argmin()

7

In [69]:
iNumpyArray.shape

(30,)

In [70]:
reshapeDizi = iNumpyArray.reshape(5,6)

In [71]:
reshapeDizi.shape

(5, 6)