In [7]:
import numpy as np

In [8]:
ilkDizi = np.arange(0,15)

In [9]:
ilkDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
ilkDizi[4]

4

In [11]:
ilkDizi[1:5]

array([1, 2, 3, 4])

In [12]:
ilkDizi[3:5] = -5

In [13]:
ilkDizi

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
baskaDizi = np.arange(0,31)

In [15]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [16]:
baskaDizi[4:7]

array([4, 5, 6])

In [17]:
slicingDizi = baskaDizi[3:15]

In [18]:
slicingDizi

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
slicingDizi[:] = 700

In [20]:
slicingDizi

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [21]:
baskaDizi

array([  0,   1,   2, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700,
       700, 700,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30])

In [22]:
ornDizi = np.arange(0,32)

In [23]:
ornDiziKopya = ornDizi.copy()

In [24]:
ornDiziKopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [25]:
ornDiziKopyaSlicing = ornDiziKopya[3:10]

In [26]:
ornDiziKopyaSlicing[:] = 20

In [27]:
ornDiziKopyaSlicing

array([20, 20, 20, 20, 20, 20, 20])

In [28]:
ornDiziKopya

array([ 0,  1,  2, 20, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [29]:
ornDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

## matrix indexler

In [30]:
ilkMatrixDizi = np.array

In [31]:
ilkListe = [[1,2,3],[1,7,3],[1,2,4]]

In [32]:
ilkMatrixDizi = np.array(ilkListe)

In [33]:
ilkMatrixDizi

array([[1, 2, 3],
       [1, 7, 3],
       [1, 2, 4]])

In [34]:
ilkMatrixDizi[0]

array([1, 2, 3])

In [35]:
ilkMatrixDizi[1][2]

3

In [36]:
 ilkMatrixDizi[1,2]

3

In [37]:
ilkMatrixDizi[0:,2]

array([3, 3, 4])

In [38]:
  yeniListe = [[0,12,3,4,5,6],[0,12,3,4,4,6],[0,12,1,4,5,5],[0,26,3,4,5,1],[0,1,3,4,5,4]]

In [40]:
yeniMatrix = np.array(yeniListe)

In [41]:
yeniMatrix

array([[ 0, 12,  3,  4,  5,  6],
       [ 0, 12,  3,  4,  4,  6],
       [ 0, 12,  1,  4,  5,  5],
       [ 0, 26,  3,  4,  5,  1],
       [ 0,  1,  3,  4,  5,  4]])

## operasyonlar

In [52]:
sonDizi = np.random.randint(1,100,20)

In [53]:
sonDizi

array([29, 51, 81, 73, 44, 53, 78, 12, 78, 13, 81, 69, 60, 16, 71, 29, 17,
       71, 64, 85])

In [54]:
sonDizi > 50

array([False,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True,  True, False,  True, False, False,  True,
        True,  True])

In [55]:
sonDizi

array([29, 51, 81, 73, 44, 53, 78, 12, 78, 13, 81, 69, 60, 16, 71, 29, 17,
       71, 64, 85])

In [56]:
sonucDizisi = sonDizi > 25

In [57]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True,  True])

In [60]:
sonDizi[sonucDizisi]

array([29, 51, 81, 73, 44, 53, 78, 78, 81, 69, 60, 71, 29, 71, 64, 85])

In [61]:
sonDizi

array([29, 51, 81, 73, 44, 53, 78, 12, 78, 13, 81, 69, 60, 16, 71, 29, 17,
       71, 64, 85])

In [62]:
sonDizi[sonDizi > 25]

array([29, 51, 81, 73, 44, 53, 78, 78, 81, 69, 60, 71, 29, 71, 64, 85])

In [63]:
sonDizi

array([29, 51, 81, 73, 44, 53, 78, 12, 78, 13, 81, 69, 60, 16, 71, 29, 17,
       71, 64, 85])

In [64]:
sonDizi = np.arange(0,24)

In [65]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [67]:
sonDizi* sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [68]:
sonDizi / sonDizi

C:\Users\furka\AppData\Local\Temp\ipykernel_2992\1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [70]:
np.max(sonDizi)

23

In [72]:
np.min(sonDizi)

0